repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier -w
        language: system
        types_or:
          - yaml
          - json
          - html
          - javascript
          - markdown
          - graphql

      - id: gofmt
        name: gofmt
        entry: gofmt -w -e -r 'interface{} -> any'
        language: system
        exclude: '(internal/mocks/.*\.go$|.*\.gen\.go|generated/.*$)'
        types_or:
          - go

      - id: go mod tidy
        name: go mod tidy
        entry: go mod tidy
        language: system
        pass_filenames: false
        types_or:
          - go
          - go-mod
          - go-sum
