version: 3

tasks:
  init:
    dir: tools
    cmds:
      - go install gotest.tools/gotestsum@latest
      - go install github.com/dkorunic/betteralign/cmd/betteralign@latest
      - go install golang.org/x/vuln/cmd/govulncheck@latest

  lint:
    - betteralign -apply ./...
    - golangci-lint run

  gen: go generate ./...

  test: gotestsum --format-hide-empty-pkg -- -count=1 -coverprofile=coverage.txt -covermode=atomic -tags assert ./...

  mod-tidy:
    cmds:
      - cmd: go mod tidy
        dir: tools
      - go mod tidy

  binary:
    internal: true
    vars:
      REF:
        sh: git describe --dirty=' (dirty)' --first-parent --all
      SHA:
        sh: git rev-parse --short HEAD
    cmds:
      - >-
        go build
        -ldflags="-X 'tyr/internal/version.Ref={{ .REF }}' -X 'tyr/internal/version.BuildDate={{ dateInZone "2006-01-02T15:04:05Z07:00" (now) "UTC" }}'" 
        -buildvcs=true {{ .EXTRA_FLAGS }} -trimpath -tags {{ .TAG }} -o {{ .OUT_PATH }}

  build:
    generates:
      - dist/tyr.exe
    sources:
      - go.mod
      - go.sum
      - "**/*.go"
    cmds:
      - task: binary
        vars:
          TAG: release
          OUT_PATH: dist/tyr.exe

  build:dev:
    generates:
      - dist/dev/server.exe
    sources:
      - go.mod
      - go.sum
      - "**/*.go"
    cmds:
      - task: binary
        vars:
          TAG: assert
          OUT_PATH: dist/dev/tmp.exe
          EXTRA_FLAGS: -race
      - cp -p dist/dev/tmp.exe dist/dev/server.exe

  dev:
    deps:
      - build:dev
    generates:
      - tmp/non-exists-file-so-it-always-run
    sources:
      - .env
      - go.mod
      - go.sum
      - "**/*.go"
    dotenv:
      - .env
    cmds:
      - dist/dev/server.exe --debug --web 127.0.0.1:8002 --config-file ./config.toml

  dev:release:
    deps:
      - build
    cmds:
      - cp dist/tyr.exe dist/tmp/release.exe
      - dist/tmp/release.exe --web 127.0.0.1:8002 --config-file ./config.toml

  pprof:
    cmds:
      - go tool pprof -http=:8001 http://127.0.0.1:8002

  pprof:block:
    cmds:
      - go tool pprof -http=:8001 http://127.0.0.1:8002/debug/pprof/block

  heap:
    cmds:
      - go tool pprof -http=:8001 http://127.0.0.1:8002/debug/pprof/heap
