version: 3

tasks:
  test: go test ./...

  build:
    generates:
      - dist/ve.exe
    sources:
      - go.mod
      - go.sum
      - "**/*.go"
      - "internal/web/static/**/*"
    cmd: go build -tags release -o dist/tyr.exe main.go

  build:dev:
    generates:
      - dist/tmp/tmp.exe
    env:
      #      CGO_ENABLED: '0'
      GORACE: halt_on_error=1
    sources:
      - .env
      - go.mod
      - go.sum
      - "**/*.go"
      - "internal/web/static/**/*"
      - "**/*.json"
    cmd: go build -tags assert -o dist/tmp/tmp.exe main.go

  dev:
    watch: true
    deps:
      - build:dev
    dotenv:
      - .env
    cmds:
      - cp dist/tmp/tmp.exe dist/tmp/server.exe
      - dist/tmp/server.exe --debug --web 127.0.0.1:8002 --config-file ./config.toml
  #
  #  dev:release:
  #    watch: true
  #    deps:
  #      - build
  #    cmds:
  #      - cp dist/tyr.exe dist/server.exe
  #      - dist/server.exe --web 127.0.0.1:8002 --config-file ./config.toml
  lint: golangci-lint run

  gen: go generate ./...

  pprof:
    cmds:
      - go tool pprof -http=:8001 http://127.0.0.1:8002

  pprof:block:
    cmds:
      - go tool pprof -http=:8001 http://127.0.0.1:8002/debug/pprof/block

  pprof:heap:
    cmds:
      - go tool pprof -http=:8001 http://127.0.0.1:8002/debug/pprof/heap

  trace:
    cmds:
      - curl http://127.0.0.1:8002/debug/pprof/trace?seconds=5 > trace.out
