version: 3

tasks:
  init:
    cmds:
      - go install gotest.tools/gotestsum@latest
      - go install github.com/dkorunic/betteralign/cmd/betteralign@latest
    dir: tools

  test: gotestsum --format-hide-empty-pkg

  build:
    generates:
      - dist/tmp/tmp.exe
    env:
      GORACE: halt_on_error=1
    sources:
      - go.mod
      - go.sum
      - "**/*.go"
    vars:
      REF:
        sh: git describe --dirty=' (dirty)' --first-parent --all
      SHA:
        sh: git rev-parse --short HEAD
    cmds:
      - >-
        go build
        -ldflags="-X 'tyr/internal/version.Ref={{ .REF }}' -X 'tyr/internal/version.BuildDate={{ dateInZone "2006-01-02T15:04:05Z07:00" (now) "UTC" }}'" 
        -buildvcs=true -trimpath -tags release -o dist/tyr.exe

  build:dev:
    generates:
      - dist/tmp/tmp.exe
    env:
      GORACE: halt_on_error=1
      GOAMD64: v3
    sources:
      - go.mod
      - go.sum
      - "**/*.go"
    vars:
      REF:
        sh: git describe --dirty=' (dirty)' --first-parent --all
      SHA:
        sh: git rev-parse --short HEAD
    cmds:
      - >-
        go build
        -ldflags="-X 'tyr/internal/version.Ref={{ .REF }}' -X 'tyr/internal/version.BuildDate={{ dateInZone "2006-01-02T15:04:05Z07:00" (now) "UTC" }}'" 
        -buildvcs=true -trimpath -tags assert -o dist/tmp/tmp.exe
      - cp dist/tmp/tmp.exe dist/tmp/server.exe

  dev:
    watch: true
    deps:
      - build:dev
    generates:
      - tmp/non-exists-file-so-it-always-run
    sources:
      - .env
      - go.mod
      - go.sum
      - "**/*.go"
    dotenv:
      - .env
    cmds:
      - dist/tmp/server.exe --debug --web 127.0.0.1:8002 --config-file ./config.toml
  #
  #  dev:release:
  #    watch: true
  #    deps:
  #      - build
  #    cmds:
  #      - cp dist/tyr.exe dist/server.exe
  #      - dist/server.exe --web 127.0.0.1:8002 --config-file ./config.toml
  lint:
    - betteralign -apply ./...
    - golangci-lint run

  gen: go generate ./...

  pprof:
    cmds:
      - go tool pprof -http=:8001 http://127.0.0.1:8002

  pprof:block:
    cmds:
      - go tool pprof -http=:8001 http://127.0.0.1:8002/debug/pprof/block

  pprof:heap:
    cmds:
      - go tool pprof -http=:8001 http://127.0.0.1:8002/debug/pprof/heap

  trace:
    cmds:
      - curl http://127.0.0.1:8002/debug/pprof/trace?seconds=5 > trace.out
