name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  main:
    name: '${{ matrix.os }} CGO=${{ matrix.CGO }}'
    runs-on: '${{ matrix.os }}-latest'
    strategy:
      matrix:
        os: [ ubuntu, windows, macos ]
        CGO: [ '0', '1' ]
    env:
      CGO_ENABLED: ${{ matrix.CGO }}
      GOTOOLCHAIN: local
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - run: go get ./...

      - run: go build -o tmp/try.exe
      - run: ./tmp/try.exe --help
      - run: go build -tags assert -o tmp/try.exe
      - run: ./tmp/try.exe --help
      - run: go build -tags release -o tmp/try.exe
      - run: ./tmp/try.exe --help
