name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest,'windows-latest','macos-latest' ]
        CGO: [ '0', '1' ]
    env:
      CGO_ENABLED: ${{ matrix.CGO }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - run: go get ./...

      - run: go build -o /dev/null
      - run: go build -tags assert -o /dev/null
      - run: go build -tags release -o /dev/null
